[package]
name = "simple_kv"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
nix = { version = "0.26", features = ["process"] }
